language: c
compiler:
           - gcc
           - clang

sudo: required
iinstall:
        - sudo apt-get update -qq
        - sudo apt-get install libevent-dev
script:
        - cd build && cmake -DCMAKE_BUILD_TYPE=Debug .. && cmake --build .

notifications:
        - irc "irc.oftc.net#libevhtp"
