# - Try to find the LibEvent config processing library
# Once done this will define
#
# LIBEVENT_FOUND - System has LibEvent
# LIBEVENT_INCLUDE_DIR - the LibEvent include directory
# LIBEVENT_LIBRARIES 0 The libraries needed to use LibEvent

set(_LIBEVENT_ROOT_HINTS
    ${LIBEVENT_ROOT}
    ${LIBEVENT_ROOT_DIR}
    )

FIND_PATH(LIBEVENT_INCLUDE_DIR NAMES event2/event.h HINTS ${_LIBEVENT_ROOT_HINTS}/include )
if (MSVC)
    set(_LIBEVENT_LIB_DIR_HINTS ${_LIBEVENT_ROOT_HINTS} ${_LIBEVENT_ROOT_HINTS}/lib )

    FIND_LIBRARY(LIBEVENT_LIBRARY NAMES libevent HINTS ${_LIBEVENT_LIB_DIR_HINTS} )
    FIND_LIBRARY(LIBEVENT_CORE_LIBRARY NAMES libevent_core HINTS ${_LIBEVENT_LIB_DIR_HINTS} )
    FIND_LIBRARY(LIBEVENT_PTHREADS_LIBRARY NAMES libevent_pthreads HINTS ${_LIBEVENT_LIB_DIR_HINTS} )
    # nmake output libevent_extras.lib
    FIND_LIBRARY(LIBEVENT_EXTRA_LIBRARY NAMES libevent_extra libevent_extras HINTS ${_LIBEVENT_LIB_DIR_HINTS} )
    # nmake no event_openssl
elseif (MINGW)
    set(_LIBEVENT_LIB_DIR_HINTS ${_LIBEVENT_ROOT_HINTS}/.libs )

    FIND_LIBRARY(LIBEVENT_LIBRARY NAMES event HINTS ${_LIBEVENT_LIB_DIR_HINTS} )
    FIND_LIBRARY(LIBEVENT_CORE_LIBRARY NAMES event_core HINTS ${_LIBEVENT_LIB_DIR_HINTS} )
    FIND_LIBRARY(LIBEVENT_PTHREADS_LIBRARY NAMES event_pthreads HINTS ${_LIBEVENT_LIB_DIR_HINTS} )
    FIND_LIBRARY(LIBEVENT_EXTRA_LIBRARY NAMES event_extra HINTS ${_LIBEVENT_LIB_DIR_HINTS} )
	FIND_LIBRARY(LIBEVENT_OPENSSL_LIBRARY NAMES event_openssl HINTS ${_LIBEVENT_LIB_DIR_HINTS} )
else()
    FIND_LIBRARY(LIBEVENT_LIBRARY NAMES event)
    FIND_LIBRARY(LIBEVENT_CORE_LIBRARY NAMES event_core)
    FIND_LIBRARY(LIBEVENT_PTHREADS_LIBRARY NAMES event_pthreads)
    FIND_LIBRARY(LIBEVENT_EXTRA_LIBRARY NAMES event_extra)
	FIND_LIBRARY(LIBEVENT_OPENSSL_LIBRARY NAMES event_openssl)
endif()

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(LibEvent DEFAULT_MSG LIBEVENT_LIBRARY LIBEVENT_INCLUDE_DIR)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(LibEventPthreads DEFAULT_MSG LIBEVENT_PTHREADS_LIBRARY LIBEVENT_INCLUDE_DIR)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(LibEventCore DEFAULT_MSG LIBEVENT_CORE_LIBRARY LIBEVENT_INCLUDE_DIR)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(LibEventExtra DEFAULT_MSG LIBEVENT_EXTRA_LIBRARY LIBEVENT_INCLUDE_DIR)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(LibEventOpenssl DEFAULT_MSG LIBEVENT_OPENSSL_LIBRARY LIBEVENT_INCLUDE_DIR)

MARK_AS_ADVANCED(LIBEVENT_INCLUDE_DIR LIBEVENT_LIBRARY LIBEVENT_PTHREADS_LIBRARY LIBEVENT_OPENSSL_LIBRARY LIBEVENT_CORE_LIBRARY LIBEVENT_EXTRA_LIBRARY)
